In [2]:
import pandas as pd
import numpy as np #library
state_crime = pd.read_csv('state_crime.csv')

In [3]:
state_crime.loc[(state_crime['Year'] == 2000)]

,State,Year,Data.Population,Data.Rates.Property.All,Data.Rates.Property.Burglary,Data.Rates.Property.Larceny,Data.Rates.Property.Motor,Data.Rates.Violent.All,Data.Rates.Violent.Assault,Data.Rates.Violent.Murder,...,Data.Rates.Violent.Robbery,Data.Totals.Property.All,Data.Totals.Property.Burglary,Data.Totals.Property.Larceny,Data.Totals.Property.Motor,Data.Totals.Violent.All,Data.Totals.Violent.Assault,Data.Totals.Violent.Murder,Data.Totals.Violent.Rape,Data.Totals.Violent.Robbery
40,Alabama,2000,4447100,4059.7,906.9,2864.8,288.0,486.2,317.2,7.4,...,128.2,180539,40331,127399,12809,21620,14107,329,1482,5702
100,Alaska,2000,626932,3682.5,621.9,2685.8,374.8,566.9,405.1,4.3,...,78.2,23087,3899,16838,2350,3554,2540,27,497,490
160,Arizona,2000,5130632,5297.8,1011.6,3444.1,842.1,531.7,347.7,7.0,...,146.3,271811,51902,176705,43204,27281,17841,359,1577,7504
220,Arkansas,2000,2673400,3670.0,802.1,2608.7,259.3,445.3,332.4,6.3,...,74.8,98115,21443,69740,6932,11904,8887,168,848,2001
280,California,2000,33871648,3118.2,656.3,1924.5,537.4,621.6,408.7,6.1,...,177.9,1056183,222293,651855,182035,210531,138418,2079,9785,60249
340,Colorado,2000,4301261,3648.6,630.8,2623.5,394.3,334.0,219.1,3.1,...,70.5,156937,27133,112843,16961,14367,9425,134,1774,3034
400,Connecticut,2000,3405565,2908.0,512.0,2011.4,384.6,324.7,189.4,2.9,...,112.5,99033,17436,68498,13099,11058,6450,98,678,3832
460,Delaware,2000,783600,3793.6,665.6,2725.9,402.1,684.4,449.2,3.2,...,177.9,29727,5216,21360,3151,5363,3520,25,424,1394
520,District of Columbia,2000,572059,5768.6,829.5,3785.4,1153.7,1507.9,801.0,41.8,...,621.3,33000,4745,21655,6600,8626,4582,239,251,3554
580,Florida,2000,15982378,4882.7,1081.8,3242.9,558.0,812.0,563.2,5.6,...,199.0,780377,172898,518298,89181,129777,90008,903,7057,31809
640,Georgia,2000,8186453,4246.4,836.6,2937.0,472.8,504.7,310.9,8.0,...,161.9,347630,68488,240440,38702,41319,25450,651,1968,13250
700,Hawaii,2000,1211537,4955.1,880.3,3570.2,504.6,243.8,119.7,2.9,...,92.7,60033,10665,43254,6114,2954,1450,35,346,1123
760,Idaho,2000,1293953,2933.7,566.5,2206.0,161.2,252.5,204.3,1.2,...,17.2,37961,7330,28545,2086,3267,2644,16,384,223
820,Illinois,2000,12419293,3585.4,659.1,2521.6,404.7,653.8,408.5,7.2,...,206.5,445278,81850,313161,50267,81196,50731,898,3926,25641
880,Indiana,2000,6080485,3402.8,676.1,2379.9,346.8,349.1,211.1,5.8,...,103.3,206905,41108,144707,21090,21230,12837,352,1759,6282
940,Iowa,2000,2926324,2967.3,558.4,2225.2,183.6,266.4,205.1,1.6,...,36.6,86834,16342,65118,5374,7796,6003,46,676,1071
1000,Kansas,2000,2688418,4019.4,799.1,2978.6,241.6,389.4,269.0,6.3,...,76.2,108057,21484,80077,6496,10470,7231,169,1022,2048
1060,Kentucky,2000,4041769,2665.2,626.2,1809.6,229.5,294.5,182.2,4.8,...,80.6,107723,25308,73141,9274,11903,7363,193,1091,3256
1120,Louisiana,2000,4468976,4741.7,1035.8,3229.9,475.9,681.1,466.6,12.5,...,168.5,211904,46289,144345,21270,30440,20851,560,1497,7532
1180,Maine,2000,1274923,2510.2,531.4,1875.1,103.7,109.6,63.9,1.2,...,19.4,32003,6775,23906,1322,1397,815,15,320,247
1240,Maryland,2000,5296486,4029.5,744.4,2745.7,539.5,786.6,493.3,8.1,...,256.0,213422,39426,145423,28573,41663,26130,430,1543,13560
1300,Massachusetts,2000,6349097,2550.0,482.0,1660.5,407.6,476.1,355.9,2.0,...,91.6,161901,30600,105425,25876,30230,22594,125,1696,5815
1360,Michigan,2000,9938444,3554.9,702.2,2291.9,560.7,555.0,359.7,6.7,...,138.0,353297,69790,227783,55724,55159,35753,669,5025,13712
1420,Minnesota,2000,4919479,3207.6,530.9,2403.7,273.0,280.8,156.7,3.1,...,75.5,157798,26116,118250,13432,13813,7709,151,2240,3713
1480,Mississippi,2000,2844658,3643.5,946.3,2452.2,245.0,360.9,221.1,9.0,...,95.0,103644,26918,69758,6968,10267,6290,255,1019,2703
1540,Missouri,2000,5595211,4037.7,745.0,2851.3,441.4,490.0,323.9,6.2,...,135.8,225919,41685,159539,24695,27419,18123,347,1351,7598
1600,Montana,2000,902195,3568.9,437.4,2957.0,210.2,311.1,252.3,2.2,...,22.5,32198,3624,26678,1896,2807,2276,20,308,203
1660,Nebraska,2000,1711263,3767.9,592.0,2870.3,305.6,327.6,231.4,3.7,...,67.0,64479,10131,49118,5230,5606,3960,63,436,1147
1720,Nevada,2000,1998257,3744.4,877.1,2208.2,659.2,524.2,247.3,6.5,...,227.3,74823,17526,44125,13172,10474,4942,129,860,4543
1780,New Hampshire,2000,1235786,2257.8,404.0,1680.0,173.8,175.4,94.7,1.8,...,36.7,27901,4992,20761,2148,2167,1170,22,522,453
1840,New Jersey,2000,8414350,2776.6,522.0,1848.8,405.9,383.8,203.2,3.4,...,161.1,233637,43924,155562,34151,32298,17099,289,1357,13553
1900,New Mexico,2000,1819046,4761.0,1173.1,3184.4,403.6,757.9,562.4,7.4,...,137.4,86605,21339,57925,7341,13786,10230,135,922,2499
1955,New York,2000,18976457,2545.7,463.4,1796.4,285.8,553.9,316.7,5.0,...,213.6,483078,87946,340901,54231,105111,60090,952,3530,40539
2015,North Carolina,2000,8049313,4421.8,1216.1,2891.8,313.9,497.6,307.0,7.0,...,156.5,355921,97888,232767,25266,40051,24715,560,2181,12595
2075,North Dakota,2000,642200,2206.6,325.9,1727.2,153.5,81.4,45.8,0.6,...,8.7,14171,2093,11092,986,523,294,4,169,56
2135,Ohio,2000,11353140,3707.7,780.7,2583.2,343.7,334.1,155.3,3.7,...,137.5,420939,88636,293277,39026,37935,17636,418,4271,15610
2195,Oklahoma,2000,3450654,4060.8,917.5,2785.4,357.8,497.8,375.5,5.3,...,75.8,140125,31661,96116,12348,17177,12958,182,1422,2615
2255,Oregon,2000,3421399,4494.7,748.8,3338.7,407.2,350.7,226.7,2.0,...,84.4,153780,25618,114230,13932,12000,7756,70,1286,2888
2315,Pennsylvania,2000,12281054,2575.3,440.4,1839.2,295.8,420.0,240.9,4.9,...,147.8,316274,54080,225869,36325,51584,29580,602,3247,18155
2375,Rhode Island,2000,1048319,3178.7,631.5,2102.2,445.0,297.7,166.2,4.3,...,88.0,33323,6620,22038,4665,3121,1742,45,412,922
2435,South Carolina,2000,4012012,4518.7,969.3,3125.2,388.5,828.1,624.5,7.3,...,155.0,181290,40319,125385,15586,33225,25054,291,1660,6220
2495,South Dakota,2000,754844,2153.0,383.7,1663.7,105.7,166.8,108.1,0.9,...,17.4,16252,2896,12558,798,1259,816,7,305,131
2555,Tennessee,2000,5689283,4183.0,990.4,2708.8,483.9,707.2,495.2,7.2,...,166.4,237985,56344,154111,27530,40233,28172,410,2186,9465
2615,Texas,2000,20851820,4410.4,906.3,3057.4,446.8,545.1,356.3,5.9,...,145.1,919658,188975,637522,93161,113653,74302,1238,7856,30257
2675,United States,2000,281421906,3618.3,728.8,2477.3,412.2,506.5,324.0,5.5,...,145.0,10182584,2050992,6971590,1160002,1425486,911706,15586,90178,408016
2735,Utah,2000,2233169,4220.3,642.5,3288.5,289.3,255.7,159.5,1.9,...,55.6,94247,14348,73438,6461,5711,3563,43,863,1242
2795,Vermont,2000,608827,2873.4,575.0,2165.5,132.9,113.5,69.8,1.5,...,19.2,17494,3501,13184,809,691,425,9,140,117
2855,Virginia,2000,7078515,2746.4,429.9,2064.8,251.6,281.7,164.3,5.7,...,88.9,194405,30434,146158,17813,19943,11631,401,1616,6295
2915,Washington,2000,5894121,4736.0,907.3,3234.6,594.1,369.7,221.3,3.3,...,98.6,279144,53476,190650,35018,21788,13043,196,2737,5812
2975,West Virginia,2000,1808344,2286.3,546.9,1556.1,183.3,316.5,254.2,2.5,...,41.4,41344,9890,28139,3315,5723,4597,46,331,749
3035,Wisconsin,2000,5363675,2972.3,469.5,2229.9,272.9,236.8,127.3,3.2,...,84.6,159424,25183,119605,14636,12700,6829,169,1165,4537
3095,Wyoming,2000,493782,3031.5,420.8,2494.6,116.0,266.5,217.5,2.4,...,14.2,14969,2078,12318,573,1316,1074,12,160,70

In [10]:
import pandas as pd
import numpy as np #library
state_crime = pd.read_csv('state_crime.csv')
#only using the columns that I am comparing in my question
columns_needed = [
    'Data.Totals.Property.Burglary',
    'Data.Totals.Property.Larceny',
    'Data.Totals.Property.Motor',
    'Data.Totals.Violent.Assault',
    'Data.Totals.Violent.Murder',
    'Data.Totals.Violent.Rape',
    'Data.Totals.Violent.Robbery'
]
#locating the states that are only in the year 2000 and only finding them in the columns_needed (.loc)
state_crime_2000 = state_crime.loc[
    state_crime['Year'] == 2000,
    ['State'] + ['Year'] + columns_needed
]
#printing the state, year, and the columns needed
state_crime_2000

,State,Year,Data.Totals.Property.Burglary,Data.Totals.Property.Larceny,Data.Totals.Property.Motor,Data.Totals.Violent.Assault,Data.Totals.Violent.Murder,Data.Totals.Violent.Rape,Data.Totals.Violent.Robbery
40,Alabama,2000,40331,127399,12809,14107,329,1482,5702
100,Alaska,2000,3899,16838,2350,2540,27,497,490
160,Arizona,2000,51902,176705,43204,17841,359,1577,7504
220,Arkansas,2000,21443,69740,6932,8887,168,848,2001
280,California,2000,222293,651855,182035,138418,2079,9785,60249
340,Colorado,2000,27133,112843,16961,9425,134,1774,3034
400,Connecticut,2000,17436,68498,13099,6450,98,678,3832
460,Delaware,2000,5216,21360,3151,3520,25,424,1394
520,District of Columbia,2000,4745,21655,6600,4582,239,251,3554
580,Florida,2000,172898,518298,89181,90008,903,7057,31809
640,Georgia,2000,68488,240440,38702,25450,651,1968,13250
700,Hawaii,2000,10665,43254,6114,1450,35,346,1123
760,Idaho,2000,7330,28545,2086,2644,16,384,223
820,Illinois,2000,81850,313161,50267,50731,898,3926,25641
880,Indiana,2000,41108,144707,21090,12837,352,1759,6282
940,Iowa,2000,16342,65118,5374,6003,46,676,1071
1000,Kansas,2000,21484,80077,6496,7231,169,1022,2048
1060,Kentucky,2000,25308,73141,9274,7363,193,1091,3256
1120,Louisiana,2000,46289,144345,21270,20851,560,1497,7532
1180,Maine,2000,6775,23906,1322,815,15,320,247
1240,Maryland,2000,39426,145423,28573,26130,430,1543,13560
1300,Massachusetts,2000,30600,105425,25876,22594,125,1696,5815
1360,Michigan,2000,69790,227783,55724,35753,669,5025,13712
1420,Minnesota,2000,26116,118250,13432,7709,151,2240,3713
1480,Mississippi,2000,26918,69758,6968,6290,255,1019,2703
1540,Missouri,2000,41685,159539,24695,18123,347,1351,7598
1600,Montana,2000,3624,26678,1896,2276,20,308,203
1660,Nebraska,2000,10131,49118,5230,3960,63,436,1147
1720,Nevada,2000,17526,44125,13172,4942,129,860,4543
1780,New Hampshire,2000,4992,20761,2148,1170,22,522,453
1840,New Jersey,2000,43924,155562,34151,17099,289,1357,13553
1900,New Mexico,2000,21339,57925,7341,10230,135,922,2499
1955,New York,2000,87946,340901,54231,60090,952,3530,40539
2015,North Carolina,2000,97888,232767,25266,24715,560,2181,12595
2075,North Dakota,2000,2093,11092,986,294,4,169,56
2135,Ohio,2000,88636,293277,39026,17636,418,4271,15610
2195,Oklahoma,2000,31661,96116,12348,12958,182,1422,2615
2255,Oregon,2000,25618,114230,13932,7756,70,1286,2888
2315,Pennsylvania,2000,54080,225869,36325,29580,602,3247,18155
2375,Rhode Island,2000,6620,22038,4665,1742,45,412,922
2435,South Carolina,2000,40319,125385,15586,25054,291,1660,6220
2495,South Dakota,2000,2896,12558,798,816,7,305,131
2555,Tennessee,2000,56344,154111,27530,28172,410,2186,9465
2615,Texas,2000,188975,637522,93161,74302,1238,7856,30257
2675,United States,2000,2050992,6971590,1160002,911706,15586,90178,408016
2735,Utah,2000,14348,73438,6461,3563,43,863,1242
2795,Vermont,2000,3501,13184,809,425,9,140,117
2855,Virginia,2000,30434,146158,17813,11631,401,1616,6295
2915,Washington,2000,53476,190650,35018,13043,196,2737,5812
2975,West Virginia,2000,9890,28139,3315,4597,46,331,749
3035,Wisconsin,2000,25183,119605,14636,6829,169,1165,4537
3095,Wyoming,2000,2078,12318,573,1074,12,160,70

In [29]:
import pandas as pd
import numpy as np #library

state_crime = pd.read_csv('state_crime.csv')

#only using the columns that I am comparing in my question
columns_needed = [
    'Data.Totals.Property.Burglary',
    'Data.Totals.Property.Larceny',
    'Data.Totals.Property.Motor',
    'Data.Totals.Violent.Assault',
    'Data.Totals.Violent.Murder',
    'Data.Totals.Violent.Rape',
    'Data.Totals.Violent.Robbery'
]

#locating the states that are only in the year 2000 and only finding them in the columns_needed (.loc)
state_crime_2000 = state_crime.loc[
    state_crime['Year'] == 2000,
    ['State'] + ['Year'] + columns_needed
]
#comparing each element in the row and producing the highest number and finding that column
#adding new columns to state_crime.csv
#gives the column name of the maximum value for each row; need 1 as if you use 0, it returns NaN; looked up on pandas
state_crime_2000['Highest_Crime'] = state_crime_2000[columns_needed].idxmax(axis=1)

#gives the maximum value in that column; need 1 as if you use 0, it returns NaN; looked up on pandas
state_crime_2000['Highest_Value'] = state_crime_2000[columns_needed].max(axis=1)

#prints the values that I want; state, crime, value
#to_string(index=False) deletes the indexing number; looked up on pandas
print(state_crime_2000[['State', 'Highest_Crime', 'Highest_Value']].to_string(index=False))

               State                Highest_Crime  Highest_Value
             Alabama Data.Totals.Property.Larceny         127399
              Alaska Data.Totals.Property.Larceny          16838
             Arizona Data.Totals.Property.Larceny         176705
            Arkansas Data.Totals.Property.Larceny          69740
          California Data.Totals.Property.Larceny         651855
            Colorado Data.Totals.Property.Larceny         112843
         Connecticut Data.Totals.Property.Larceny          68498
            Delaware Data.Totals.Property.Larceny          21360
District of Columbia Data.Totals.Property.Larceny          21655
             Florida Data.Totals.Property.Larceny         518298
             Georgia Data.Totals.Property.Larceny         240440
              Hawaii Data.Totals.Property.Larceny          43254
               Idaho Data.Totals.Property.Larceny          28545
            Illinois Data.Totals.Property.Larceny         313161
             Indiana Data.Totals.Property.Larceny         144707
                Iowa Data.Totals.Property.Larceny          65118
              Kansas Data.Totals.Property.Larceny          80077
            Kentucky Data.Totals.Property.Larceny          73141
           Louisiana Data.Totals.Property.Larceny         144345
               Maine Data.Totals.Property.Larceny          23906
            Maryland Data.Totals.Property.Larceny         145423
       Massachusetts Data.Totals.Property.Larceny         105425
            Michigan Data.Totals.Property.Larceny         227783
           Minnesota Data.Totals.Property.Larceny         118250
         Mississippi Data.Totals.Property.Larceny          69758
            Missouri Data.Totals.Property.Larceny         159539
             Montana Data.Totals.Property.Larceny          26678
            Nebraska Data.Totals.Property.Larceny          49118
              Nevada Data.Totals.Property.Larceny          44125
       New Hampshire Data.Totals.Property.Larceny          20761
          New Jersey Data.Totals.Property.Larceny         155562
          New Mexico Data.Totals.Property.Larceny          57925
            New York Data.Totals.Property.Larceny         340901
      North Carolina Data.Totals.Property.Larceny         232767
        North Dakota Data.Totals.Property.Larceny          11092
                Ohio Data.Totals.Property.Larceny         293277
            Oklahoma Data.Totals.Property.Larceny          96116
              Oregon Data.Totals.Property.Larceny         114230
        Pennsylvania Data.Totals.Property.Larceny         225869
        Rhode Island Data.Totals.Property.Larceny          22038
      South Carolina Data.Totals.Property.Larceny         125385
        South Dakota Data.Totals.Property.Larceny          12558
           Tennessee Data.Totals.Property.Larceny         154111
               Texas Data.Totals.Property.Larceny         637522
       United States Data.Totals.Property.Larceny        6971590
                Utah Data.Totals.Property.Larceny          73438
             Vermont Data.Totals.Property.Larceny          13184
            Virginia Data.Totals.Property.Larceny         146158
          Washington Data.Totals.Property.Larceny         190650
       West Virginia Data.Totals.Property.Larceny          28139
           Wisconsin Data.Totals.Property.Larceny         119605
             Wyoming Data.Totals.Property.Larceny          12318

In [ ]:
import matplotlib.pyplot as plt

In [28]:
import pandas as pd
import numpy as np #library

state_crime = pd.read_csv('state_crime.csv')

#only using the columns that I am comparing in my question
columns_needed = [
    'Data.Totals.Property.Burglary',
    'Data.Totals.Property.Larceny',
    'Data.Totals.Property.Motor',
    'Data.Totals.Violent.Assault',
    'Data.Totals.Violent.Murder',
    'Data.Totals.Violent.Rape',
    'Data.Totals.Violent.Robbery'
]

#locating the states that are only in the year 2000 and only finding them in the columns_needed (.loc)
state_crime_2000 = state_crime.loc[
    state_crime['Year'] == 2000,
    ['State'] + ['Year'] + columns_needed
]
#comparing each element in the row and producing the highest number and finding that column
#adding new columns to state_crime.csv
#gives the column name of the maximum value for each row; need 1 as if you use 0, it returns NaN; looked up on pandas
state_crime_2000['Highest_Crime'] = state_crime_2000[columns_needed].idxmax(axis=1)

#gives the maximum value in that column; need 1 as if you use 0, it returns NaN; looked up on pandas
state_crime_2000['Highest_Value'] = state_crime_2000[columns_needed].max(axis=1)

#want to now find the highest value of all in the higest value in this list
#need axis 0 becuase you are only looking at the maximum in 1 column; looked up on pandas
highest_of_all = state_crime_2000['Highest_Value'].idxmax(axis=0)

#now that we have found it, in the column, we need to find the row; looked up on pandas
highest_of_all_state = state_crime_2000.loc[highest_of_all, ['State', 'Highest_Crime', 'Highest_Value']]

#prints the values that I want; state, crime
#to_string(index=False) deletes the indexing number; looked up on pandas
print(highest_of_all_state.to_string(index=False))

               United States
Data.Totals.Property.Larceny
                     6971590